третий спринт
SberKotlinSchool/Sprint-3 pull request #16
Opened 2022-09-28 07:28 UTC by stasyanich

2022-09-28 07:32 UTC, shariktlt-devops approved these changes
:ok: build ok, see: https://jenkins.shariktlt.ru/job/kotlin_school_2/job/PR_BUILDER/153/

2022-10-03 20:42 UTC, SberKotlinSchool commented on oop/src/main/kotlin/ru/sber/oop/DataClasses.kt
> +    print(user1.equals(user3))
у юзеров разные города, но все равно equals = true, а на самом деле юзеры разные

2022-10-03 20:42 UTC, SberKotlinSchool commented on oop/src/main/kotlin/ru/sber/oop/Inheritance.kt
> +open class Room(val name: String, val size: Int) {
отсутствует вторичный конструктор, который требуется в задании

2022-10-03 20:42 UTC, SberKotlinSchool commented on oop/src/main/kotlin/ru/sber/oop/Inheritance.kt
> +    override fun load() = "parents must be open"
в задании требуется чтобы функцию load этого класса нельзя было бы переопределить в наследниках

2022-10-26 10:52 UTC, shariktlt-devops requested changes
:no_entry: build failed, see: https://jenkins.shariktlt.ru/job/kotlin_school_2/job/PR_BUILDER/387/

2022-10-26 11:10 UTC, shariktlt-devops requested changes
:no_entry: build failed, see: https://jenkins.shariktlt.ru/job/kotlin_school_2/job/PR_BUILDER/388/

2022-10-28 05:45 UTC, shariktlt-devops requested changes
:no_entry: build failed, see: https://jenkins.shariktlt.ru/job/kotlin_school_2/job/PR_BUILDER/399/

2022-10-28 05:53 UTC, shariktlt-devops approved these changes
:ok: build ok, see: https://jenkins.shariktlt.ru/job/kotlin_school_2/job/PR_BUILDER/401/

2025-12-26 14:07 UTC, closed without merging