qa
SberKotlinSchool/Sprint-3 pull request #31
Opened 2022-10-25 18:58 UTC by albertincx

2022-10-25 18:59 UTC, shariktlt-devops approved these changes
:ok: build ok, see: https://jenkins.shariktlt.ru/job/kotlin_school_2/job/PR_BUILDER/382/

2022-10-27 15:24 UTC, shariktlt-devops approved these changes
:ok: build ok, see: https://jenkins.shariktlt.ru/job/kotlin_school_2/job/PR_BUILDER/395/

2022-10-28 16:17 UTC, shariktlt-devops requested changes
:no_entry: build failed, see: https://jenkins.shariktlt.ru/job/kotlin_school_2/job/PR_BUILDER/414/

2022-10-28 16:22 UTC, shariktlt-devops requested changes
:no_entry: build failed, see: https://jenkins.shariktlt.ru/job/kotlin_school_2/job/PR_BUILDER/416/

2022-10-28 16:26 UTC, shariktlt-devops approved these changes
:ok: build ok, see: https://jenkins.shariktlt.ru/job/kotlin_school_2/job/PR_BUILDER/417/

2022-10-29 06:45 UTC, shariktlt-devops approved these changes
:ok: build ok, see: https://jenkins.shariktlt.ru/job/kotlin_school_2/job/PR_BUILDER/421/

2022-11-06 09:06 UTC, shariktlt-devops approved these changes
:ok: build ok, see: https://jenkins.shariktlt.ru/job/kotlin_school_2/job/PR_BUILDER/532/

2022-11-07 10:07 UTC, shariktlt-devops approved these changes
:ok: build ok, see: https://jenkins.shariktlt.ru/job/kotlin_school_2/job/PR_BUILDER/601/

2022-11-07 10:09 UTC, shariktlt-devops approved these changes
:ok: build ok, see: https://jenkins.shariktlt.ru/job/kotlin_school_2/job/PR_BUILDER/602/

2022-11-07 20:09 UTC, SberKotlinSchool commented on qa/src/test/kotlin/ru/sber/qa/CertificateRequestTest.kt
> +        every { Scanner.getScanData() } returns ByteArray(1)
отсутствуют проверки того, что этот метод вызывается при обработке запроса

2022-11-07 20:12 UTC, SberKotlinSchool commented on qa/src/test/kotlin/ru/sber/qa/HrDepartmentTest.kt
> +            every { certificateRequest.certificateType } returns CertificateType.NDFL
не стоит смешивать установку моков и ассерты

2022-11-07 20:16 UTC, SberKotlinSchool commented on qa/src/test/kotlin/ru/sber/qa/HrDepartmentTest.kt
> +    fun `success push and poll`() {
здесь тестирование второго метода завязано на успешное исполнение первого

2022-11-08 04:48 UTC, shariktlt-devops approved these changes
:ok: build ok, see: https://jenkins.shariktlt.ru/job/kotlin_school_2/job/PR_BUILDER/622/

2022-11-08 04:49 UTC, albertincx commented on qa/src/test/kotlin/ru/sber/qa/CertificateRequestTest.kt
> +        every { Scanner.getScanData() } returns ByteArray(1)
По сканеру есть отдельный тест

2022-11-10 18:50 UTC, SberKotlinSchool commented on qa/src/test/kotlin/ru/sber/qa/HrDepartmentTest.kt
> +    fun `success push and poll`() {
все еще есть зависимость от другого метода - если его поведение изменится, метод processNextRequest не получится

2022-11-10 18:57 UTC, albertincx commented on qa/src/test/kotlin/ru/sber/qa/HrDepartmentTest.kt
> +    fun `success push and poll`() {
посмотрите пожалуйста вот это обновление https://github.com/SberKotlinSchool/Sprint-3/pull/31/files/e44332f5e9edc1031e367bef37d649f75b26db74..a50d079c6b973e6b88fdb0c3b6d97e010c8af543
так норм?

2022-11-13 18:54 UTC, albertincx commented on qa/src/test/kotlin/ru/sber/qa/CertificateRequestTest.kt
> +        every { Scanner.getScanData() } returns ByteArray(1)
> отсутствуют проверки того, что этот метод вызывается при обработке запроса

Добавлено

2022-11-13 18:55 UTC, albertincx commented on qa/src/test/kotlin/ru/sber/qa/HrDepartmentTest.kt
> +            every { certificateRequest.certificateType } returns CertificateType.NDFL
Исправлено

2022-11-13 18:55 UTC, albertincx commented on qa/src/test/kotlin/ru/sber/qa/HrDepartmentTest.kt
> +    fun `success push and poll`() {
Тут есть кто-нибудь?

2022-11-14 13:36 UTC, SberKotlinSchool commented on qa/src/test/kotlin/ru/sber/qa/HrDepartmentTest.kt
> +    fun `success push and poll`() {
> посмотрите пожалуйста вот это обновление https://github.com/SberKotlinSchool/Sprint-3/pull/31/files/e44332f5e9edc1031e367bef37d649f75b26db74..a50d079c6b973e6b88fdb0c3b6d97e010c8af543 так норм?

В этих изменениях вызов метода receiveRequest был вынесен из основного теста в блок BeforeTest - но поведение теста при этом не поменялось: прежде чем проверить processNextRequest происходит прямой вызов receiveRequest.

Чем это плохо:  если метод receiveRequest изменится (перестанет заполнять inbox), то тест `success processNextRequest` упадет, хотя на самом деле тестируемый метод processNextRequest продолжает функционировать как надо

PS: здесь нужно использовать рефлексию

2022-11-14 18:10 UTC, shariktlt-devops approved these changes
:ok: build ok, see: https://jenkins.shariktlt.ru/job/kotlin_school_2/job/PR_BUILDER/784/

2022-11-14 18:10 UTC, albertincx commented on qa/src/test/kotlin/ru/sber/qa/HrDepartmentTest.kt
> +    fun `success push and poll`() {
Готово!

2022-11-17 12:01 UTC, SberKotlinSchool commented on qa/src/test/kotlin/ru/sber/qa/HrDepartmentTest.kt
> +    fun `success push and poll`() {
почти)

2022-11-17 12:02 UTC, SberKotlinSchool commented on qa/src/test/kotlin/ru/sber/qa/HrDepartmentTest.kt
> +        HrDepartment.receiveRequest(certificateR)
вот этой строки здесь быть не должно
вместо нее следовало добавить элемент в incomeBox напрямую ниже

2023-02-10 17:57 UTC, closed without merging